# Generated by Django 4.2.5 on 2023-09-12 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ustalar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ustalar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ustalar',
            name='order_name',
        ),
        migrations.RemoveField(
            model_name='ustalar',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ustalar',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ustalar',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ustalar',
            name='status_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ustalar',
            name='usta_last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterModelTable(
            name='ustalar',
            table='Ustalar',
        ),
        migrations.CreateModel(
            name='Orderlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(default='', max_length=200)),
                ('order_payment', models.IntegerField(default=0)),
                ('description', models.TextField(verbose_name='you can type anything')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
                ('ustalar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ustalar')),
            ],
            options={
                'db_table': 'Orderlar',
            },
        ),
    ]
